"""fase5_prompts

Revision ID: 947d4ca8428f
Revises: 0fe6a365787c
Create Date: 2026-08-14 09:52:20.437281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '947d4ca8428f'
down_revision: Union[str, Sequence[str], None] = '0fe6a365787c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_registry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('status', sa.dialects.postgresql.ENUM('ACTIVE', 'INACTIVE', 'MIGRATING', name='statusenum', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_registry')
    # ### end Alembic commands ###
